name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: example. email@example.com
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What module version did this bug occur on?
      placeholder: example. 0.0.1
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Textual explanation of the error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Relevant code
      description: |
        Please copy and paste any relevant code used to produce the given error.
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
