# This workflow will automatically tag the main branch on PR closure with the name from the branch name

name: Tag on PR Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create tag
        run: |
          echo "Git config for bot"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          echo "Get module tag; GITHUB_HEAD_REF is the name of the branch that merged"
          MODULE_TAG="${GITHUB_HEAD_REF#*/}"

          echo "Get repository tag"
          REPO_TAG=$(grep ^version pyproject.toml | sed -r 's/^version = "(.*)"(.*)/\1/g')

          echo "Creating tags"
          .github/scripts/create-tag.sh "$MODULE_TAG" "$REPO_TAG"
