# This workflow will check if the tag from the branch already exists or not (and will fail if so)

name: Check Tag on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check tag
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          MODULE_TAG="${BRANCH_NAME#*/}"
          REPO_TAG=$(grep ^version pyproject.toml | sed -r 's/^version = "(.*)"(.*)/\1/g')
          .github/scripts/check-tag.sh "$MODULE_TAG" "$REPO_TAG"
